### ISSUE TITLE
Dockerfile for building proxy image

### ISSUE THREAD

**Issue by yizhengx** [aeraki-mesh/meta-protocol-proxy#112]
Hi, is there any Dockerfile available for building proxy image using bazel-bin/envoy? Something similar to this https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxyv2. And is there any specific requirement or command to build the proxy image? Thanks!

**Comment by 2011aad** [comment]
Is there any instructions provided? I'm also stuck here. Thanks.
