### ISSUE TITLE
GitHub workflow to run build for PRs

### ISSUE THREAD

**Issue by zhaohuabing** [aeraki-mesh/meta-protocol-proxy#52]
Currently, there's no auto building for new PRs. We need to set up an appropriate github workflow with actions to run auto building for PRs to make sure the new PRs can pass building.

**Comment by zhaohuabing** [comment]
We can use docker build image in the github CI.

https://github.com/aeraki-mesh/meta-protocol-proxy#build-metaprotocol-proxy-using-docker

**Comment by huanghuangzym** [comment]
i want to take this

**Comment by huanghuangzym** [comment]
it seems can not build successful in master with aeraki/meta-protocol-proxy-build:2022-0429-0
![image](https://user-images.githubusercontent.com/15240576/183847215-e65b2a7f-756c-4076-9ca7-75c381b3851d.png)

https://github.com/huanghuangzym/meta-protocol-proxy/runs/7762001559?check_suite_focus=true

**Comment by huanghuangzym** [comment]
[WeOpen Star] i would like to help
