### ISSUE TITLE
dubbo request mutation support

### ISSUE THREAD

**Issue by panniyuyu** [aeraki-mesh/meta-protocol-proxy#54]
Meta-protocol-proxy could route by header with dubbo protocol. I prefer to request dubbo header mutation support, which is necessary.

**Comment by zhaohuabing** [comment]
@panniyuyu Dubbo header mutation has been supported. Please feel free to use it and welcome to give feedback.

https://www.aeraki.net/zh/docs/v1.1/tutorials/header-mutation/

**Comment by zhaohuabing** [comment]
Close since dubbo header mutation has alreay been implmented.
