### ISSUE TITLE
is meta-protocol-proxy same as a plugin for envoy that can support more protocol?

### ISSUE THREAD

**Issue by yichouchou** [aeraki-mesh/meta-protocol-proxy#68]
i am sorry i want to know how it works, is it like a plugin working on the envoy,handle stream from listener to router?

**Comment by zhaohuabing** [comment]
@yichouchou You can find some very useful information in the below links:

https://www.aeraki.net/img/2022-03-30-aeraki-mesh-winter-olympics-practice/slides.pdf

https://www.aeraki.net/zh/blog/2022/aeraki-mesh-winter-olympics-practice/
