### ISSUE TITLE
仅在Envoy中编译meta-protocol-proxy

### ISSUE THREAD

**Issue by hbgongen** [aeraki-mesh/meta-protocol-proxy#69]
meta-protocol-proxy可以单纯的不引入istio的库，仅仅作为network级别的filter在envoy代码中编译吗？请赵老师帮忙看看，当然我也可以慢慢自己移植代码过去。想问赵老师有没有比较方便的方法，想引入该filter作为我们私有协议的tcp框架。谢谢赵老师，希望也能为项目贡献代码。

**Comment by zhaohuabing** [comment]
可以修改 BUILD 和 WORKSPACE，把 istio proxy 相关的代码去掉就行。
